# Generated by Django 4.1 on 2022-08-15 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('town', models.CharField(blank=True, max_length=500, null=True, verbose_name='Town/City')),
                ('country', models.CharField(blank=True, max_length=500, null=True, verbose_name='Country')),
                ('longitude', models.CharField(blank=True, max_length=500, null=True, verbose_name='Longitude')),
                ('latitude', models.CharField(blank=True, max_length=500, null=True, verbose_name='Latitude')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
