# Generated by Django 4.1 on 2022-08-18 15:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_locator_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField(max_length=1000)),
                ('rating', models.CharField(choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], default='5', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='locator',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='locator',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.BigIntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
