# Generated by Django 4.1 on 2022-08-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_address_locator_freeformaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='locator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.locator'),
        ),
    ]
